# Site Settings
# Do not use trailing slash (i.e. "/Sample"). For skipping base URL, leave empty quotes ("")
baseurl: ""

# Features Setting
# Turn subpages on or off
publications: True
presentations: True
blog: True

# Language of the website
lang: en

# Search engine optimization settings
title: Omri Abarbanel
tagline: 
description: 
author: 
twitter:
  username: chrjabs
  card: A jekyll theme for academic portfolios
logo: /assets/img/smile.png
social:
  name: Christoph Jabs
  links:
    - https://twitter.com/chrjabs
    - https://github.com/chrjabs
locale: en_GB

# Page Settings
theme_settings:
  title: Omri abarbanel

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS
  languages_title: LANGUAGES

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "6.7.1"
  integrity: "sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ=="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
